### PR TITLE
Fix git status test for recent git versions

### PR DESCRIPTION
**Pull request by garrison**
Deal with recent change at git/git@7560f547e614.

### CODE REVIEW

**Comment by garrison** [comment]
Bump.

**Comment by tkelman** [comment]
would be better to have it search for either old or new outputs

**Comment by garrison** [comment]
`up.to.date` is a regex that matches either output.  Not knowing precisely what you're after, I've changed it to `up[- ]to[- ]date`, which is more restrictive.

**Comment by tkelman** [comment]
ah right, I lose track of which/whether flags you need to make grep do regexes instead of exact

**Pull request merged**
